### ISSUE TITLE
TypeError: undefined is not a constructor (evaluating 'new brorand.Rand()')

### ISSUE THREAD

**Issue by Kishanjvaghela** [tradle/react-native-crypto#15]
I am using **react-native-crypto** with **rn-nodeify**. but got following error

`Requiring module "react-native-crypto/index.js", which threw an exception: TypeError: undefined is not a constructor (evaluating 'new brorand.Rand()')`

![screenshot from 2017-06-27 19-39-34](https://user-images.githubusercontent.com/11232063/27591892-ba5bc128-5b70-11e7-9ccc-bfff18d792a4.png)

**Comment by mikhaildobs** [comment]
Hi, we are working on RN Ethereum starter and just had the same issue with import of ethereumjs-wallet lib. 
Adding one line with "require("crypto")" above the import fixed the problem. 
See here - https://gitlab.com/sashamihaha/rn-ethereum-starter/commit/69a96ee8bdc9dc9ee6dae887b2e77f24284e7c27#L5
Maybe that will also help you.

**Comment by claykohut** [comment]
Did you ever figure this out @Kishanjvaghela ?

**Comment by nomoreboredom** [comment]
following this as well, requiring as @Dobrokhvalov noted fixes the problem but I only see white screen

**Comment by mvayngrib** [comment]
@Kishanjvaghela does @Dobrokhvalov's fix work for you? If not, send me a link to your project, I can take a quick look.

@Dobrokhvalov maybe we should add `require('crypto')` to the crypto section of `shim.js`?
 Currently it only gets run when not remotely debugging.

**Comment by claykohut** [comment]
I was just able to fix by adding the following to shim.js
```
global.crypto = require('crypto')
global.crypto.getRandomValues = function(byteArray) {
  for (let i = 0; i < byteArray.length; i++) {
    byteArray[i] = Math.floor(256 * Math.random());
  }
}
```
Before adding the getRandomValues method, the app would only work when remotely debugging

**Comment by mvayngrib** [comment]
@claykohut oof, you don't want to do that! rn-nodeify already shims [getRandomValues](https://github.com/mvayngrib/rn-nodeify/blob/master/shim.js#L49) with a secure implementation backed by either the iOS/Android native rng, or sjcl's implementation seeded with the native rng. Just make sure to import `shim.js` in your project, as early as possible

**Comment by claykohut** [comment]
Thanks for the heads up @mvayngrib ! Any idea why my shim.js didnt already have that in it? 

I've now manually copied the shim.js you linked to over to my shim.js -- previously it looked like:

```

if (typeof __dirname === 'undefined') global.__dirname = '/'
if (typeof __filename === 'undefined') global.__filename = ''
if (typeof process === 'undefined') {
  global.process = require('process')
} else {
  var bProcess = require('process')
  for (var p in bProcess) {
    if (!(p in process)) {
      process[p] = bProcess[p]
    }
  }
}

process.browser = false
if (typeof Buffer === 'undefined') global.Buffer = require('buffer').Buffer

// global.location = global.location || { port: 80 }
var isDev = typeof __DEV__ === 'boolean' && __DEV__
process.env['NODE_ENV'] = isDev ? 'development' : 'production'
if (typeof localStorage !== 'undefined') {
  localStorage.debug = isDev ? '*' : ''
}
```

**Comment by mvayngrib** [comment]
yea, i forget when i added the crypto stuff to `shim.js`. `rn-nodeify` doesn't overwrite your shim.js, so I guess u missed out on an update. rn-nodeify should probably export the shim in a better way, e.g. recommend apps to require it via `import 'rn-nodeify/shim'` instead of recommending copying it over.

**Comment by dylanbathurst** [comment]
Not sure if everyone has got this working yet but I had the same problem and after messing with it for a while I got it working. 

1. `rm -rf node_modules`
2. `rm shim.js`
3. `npm install`
4. `rn-nodeify --hack --install`

And it worked! A couple things to note. 
1. [I had hacked `bignumber.js`](https://github.com/ethereum/web3.js/issues/576#issuecomment-285116522) (that's required by web3.js) a while back to work with the proper crypto library, but removed the hack since `rn-nodeify` solves the issue. 
2. When building from xcode on a simulator or device I made sure to do a hard clean of the build directory (option + shift + command + k)

I'm not 100% sure what combination of all of this worked but it's currently working for me.

**Comment by mvayngrib** [comment]
looks like this is now working for people. The crypto shim has been moved over to a more sensible place in `react-native-crypto`, where it's loaded automatically. If this is still an issue for someone, we'll reopen

**Comment by sreeksp** [comment]
@claykohut @mvayngrib  
it shows me a blank white screen . No errors though. 
this is how my shim.js looks

```
if (typeof __dirname === 'undefined') global.__dirname = '/'
if (typeof __filename === 'undefined') global.__filename = ''
if (typeof process === 'undefined') {
  global.process = require('process')
} else {
  const bProcess = require('process')
  for (var p in bProcess) {
    if (!(p in process)) {
      process[p] = bProcess[p]
    }
  }
}

process.browser = false
if (typeof Buffer === 'undefined') global.Buffer = require('buffer').Buffer

// global.location = global.location || { port: 80 }
const isDev = typeof __DEV__ === 'boolean' && __DEV__
process.env['NODE_ENV'] = isDev ? 'development' : 'production'
if (typeof localStorage !== 'undefined') {
  localStorage.debug = isDev ? '*' : ''
}

```
Am i missing anything?

**Comment by mvayngrib** [comment]
@sreeksp not enough information :) Did you check for errors both in the dev tools console and in the react-native packager's?

**Comment by ahmb84** [comment]
Hello!
I've resolved this issue by importing crypto just after shim.js
This is my app.js
```javascript
import "./shim";
import crypto from "crypto";
import React from "react";
import App from "./js/App";

export default class App1 extends React.Component {
  render() {
    return <App />;
  }
}
```

**Comment by devonwesley** [comment]
Thanks @dylanbathurst and @ahmb84 , a combination of those 2  suggestions helped me out.

**Comment by micimize** [comment]
I've tried all the suggestions here a number of times, with no results. I have no idea what the problem is. `"react-native": "0.51.0"`, `"react-native-crypto": "^2.1.2"`

**Comment by mvayngrib** [comment]
@micimize did you follow the suggested workflow from the readme? Can you run the sample project at https://github.com/mvayngrib/rnctest2 ?

**Comment by micimize** [comment]
@mvayngrib Got it working. What ended up working was deleting all local files, running `yarn cache clean`, deleting everything in my `$TMPDIR`, and reinstalling everything. I still have no idea what the problem was, but I don't think it was any of the shim toolchain.
FWIW, I'm now using babel transforms in place of `rn-nodeify` and it's working fine for my limited use case:
```js
{ // .babelrc
  "presets": ["react-native"],
  "plugins": [
    "babel-plugin-react-native-nodeify-hack",
    ["rewrite-require", {
      "aliases": {
        "crypto": "react-native-crypto",
        "stream": "stream-browserify",
        "vm": "vm-browserify"
      }
    }]
  ]
}
```
```js
// index.js
require('crypto')
import process from 'process'
import buffer from 'buffer'
// ...
```

**Comment by mvayngrib** [comment]
@micimize great to hear! Yes, for some cases rewrite-require is enough. But due to a number of incompatibilities between the react-native packager and webpack/browserify, there's a number of hacks/patches rn-nodeify uses (see https://github.com/tradle/rn-nodeify/blob/master/pkg-hacks.js)

**Comment by zachgibb** [comment]
[This PR](https://github.com/indutny/brorand/pull/9) fixed this issue for me.

My project is using `react-native-bip39` and `react-native-bitcoinjs-lib`, and I was able to get this working using that fix along with the babel transforms you suggested @micimize.

For anyone also running into this issue, that doesn't want to use rn-nodeify for whatever reason, here is the process that worked for me:

## Install
`yarn add` all of these subsequent modules.

- `assert`
- `babel-plugin-rewrite-require`
- `react-native-bip39`
- `react-native-bitcoinjs-lib`
- `react-native-crypto`
- `react-native-os`
- `react-native-process-shim`
- `react-native-randombytes`
- `react-native-stream`
- `vm-browserify`

then, manually add this line to your dependencies in `package.json`:

```
  "brorand-shim": "https://github.com/HoardInvest/brorand",
```

We will later use this to alias `brorand` calls to this shimmed version, which will resolve the `new brorand.Rand()` error.


## Link
After install, `react-native link` each of these modules.

- `react-native-os`
- `react-native-randombytes`

## File changes

#### Process shim
this shim must be loaded before bip39 or the bitcoin lib, to correctly initialize the "process" global variable that is expected to be available by their dependencies

```
import 'react-native-process-shim';
```

#### .babelrc

With `babel-plugin-rewrite-require`, we can redirect any of the require or import calls of the alias we define to the module we give.

We will use the normal shims for `crypto`, `stream`, and `vm`, but add our new `brorand` shim here as well. We don't need to alias `assert`, since that is available just through having it as one of our dependencies.

```
{
  // the rest of your .babelrc file

  "plugins": [

    // other plugins you might have

    ["rewrite-require", {
      "aliases": {
        "brorand": "brorand-shim",
        "crypto": "react-native-crypto",
        "stream": "react-native-stream",
        "vm": "vm-browserify"
      }
    }]

  ],
}
```
