### ISSUE TITLE
error: bundling failed: Error: EISDIR: illegal operation on a directory

### ISSUE THREAD

**Issue by eugeneedwardkim** [tradle/react-native-crypto#23]
I followed the installation directions given for react-native-crypto and update request's crypto calls to:
import crypto from 'react-native-crypto'; 

With that being said, I am running into the error in the title when I try to use the package depending on request. 

I'm pretty green in this area, so I could be doing something wrong. Any thoughts?

**Comment by mvayngrib** [comment]
@eugeneedwardkim not sure what causes your specific error, but generally I would avoid manually modifying code in the dep tree. [rn-nodeify](https://github.com/tradle/rn-nodeify) makes it so that the request module can use `require('crypto')`, and it will get mapped to `react-native-crypto` automatically.
